spring:
  datasource:
    url: jdbc:h2:mem:url-shorter
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    token:
      secret-key: localjwtsecretkeyforaccesstokenlocaljwtsecretkeyforaccesstoken
      expire-length: 1800000
      refresh-secret-key: localjwtsecretkeyforrefreshtokenlocaljwtsecretkeyforrefreshtoken
      refresh-expire-length: 259200000

  data:
    redis:
      port: 16379
      host: localhost

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace
